function [results, passed, priority] = cocosim_guidelines_na_0004(model)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Copyright (c) 2019 United States Government as represented by the
    % Administrator of the National Aeronautics and Space Administration.
    % All Rights Reserved.
    % Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>,
    %         Khanh Trinh <khanh.v.trinh@nasa.gov>
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % ORION GN&C MATLAB/Simulink Standards
    % na_0004: Simulink model appearance
    
    priority = 3;
    results = {};
    passed = 1;
    totalFail = 0;
    item_titles = {...
        'View Options: Model Browser set to unchecked', ...
        'View Options: Screen color set to white',...
        'View Options: Status bar set to checked',...
        'View Options: Tool bar set to on',...
        'View Options: Zoom factor set to normal (100%)',...
        'Block Display Options: Execution Context Indicator set to unchecked',...
        'Block Display Options: Library Link Display set to none',...
        'Block Display Options: Show Linearization Annotations set to checked',...
        'Block Display Options: Show Model Reference Block IO set to unchecked',...
        'Block Display Options: Show Model Reference Block Version set to unchecked',...
        'Block Display Options: Sample Time Colors set to off',...
        'Block Display Options: Sorted Order set to unchecked',...
        'Signal Display Options: Show Port Data Types set to unchecked',...
        'Signal Display Options: Show Line Dimensions set to unchecked',...
        'Signal Display Options: Show Storage Class set to unchecked',...
        'Signal Display Options: Show Test Point Icons set to checked',...
        'Signal Display Options: Show Viewer Icons set to checked',...
        'Signal Display Options: Wide Non-scalar Lines set to checked',...
        'Simulation: Simulation Mode set normal'...
        };
    param_names = {...
        'ModelBrowserVisibility', ...
        'ScreenColor',...
        'StatusBar',...
        'ToolBar',...
        'ZoomFactor',...
        'ExecutionContextIcon',...
        'LibraryLinkDisplay',...
        'ShowLinearizationAnnotations',...
        'ShowModelReferenceBlockIO',...
        'ShowModelReferenceBlockIO',...   %TODO check why this is the same as above
        'SampleTimeColors',...
        'SortedOrder',...
        'ShowPortDataTypes',...
        'ShowLineDimensions',...
        'ShowLineDimensions',...             %TODO check why this is the same as above   
        'ShowTestPointIcons',...
        'ShowViewerIcons',...
        'WideLines',...
        'SimulationMode'...
        };
    param_values = {...
        'on',...            % ModelBrowserVisibility
        'white' ...         % ScreenColor
        'on',...            % StatusBar
        'on',...            % ToolBar
        '100',...           % ZoomFactor
        'off',...           % ExecutionContextIcon
        'none',...          % LibraryLinkDisplay
        'on',...            % ShowLinearizationAnnotations
        'off',...           % ShowModelReferenceBlockIO
        'off',...           % ShowModelReferenceBlockIO
        'off',...           % SampleTimeColors
        'off',...           % SortedOrder
        'off',...           % ShowPortDataTypes
        'off',...           % ShowLineDimensions
        'off',...           % ShowLineDimensions
        'on',...            % ShowTestPointIcons
        'on',...            % ShowViewerIcons
        'on',...            % WideLines
        'normal'...        % SimulationMode
        };
    
    subtitles = cell(length(item_titles)+1, 1);
    for i=1:length(item_titles)
        item_title = item_titles{i};
        param = get_param(gcs, param_names{i});
        if ~strcmp(param, param_values{i})
            fsList = {model};
        else
            fsList = {};
        end
        [subtitles{i+1}, numFail] = ...
            GuidelinesUtils.process_find_system_results(fsList,item_title,...
            true);
        totalFail = totalFail + numFail;
    end
    
    if totalFail > 0
        passed = 0;
        color = 'red';
    else
        color = 'green';
    end
    title = 'na_0004: Simulink model appearance';
    description_text = [...
        'The model appearance settings should conform to the '...
        'following guidelines when the model is released. The user ',...
        'is free to change the settings during the development process'];
    description = HtmlItem(description_text, {}, 'black', 'black');   
    subtitles{1} = description;
    results{end+1} = HtmlItem(title, subtitles, color, color);
end


