%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (c) 2019 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% compare Simulin outputs and Lustre outputs
function [valid, cex_msg, diff_name, diff_value] = ...
        compare_Simu_outputs_with_Lus_outputs(...
        input_dataSet, ...
        yout,...
        outputs_array, ...
        eps, ...
        time)
    [valid, cex_msg, diff_name, diff_value, ~] = ...
        LustrecUtils.compare_slx_out_with_lusORslx_out(...
        input_dataSet, ...
        yout,...
        [], ...
        outputs_array, ...
        eps, ...
        time);
end

