%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (c) 2019 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
%% verification file
function verif_lus_path = create_mutant_verif_file(...
        lus_file_path,...
        mutant_lus_fpath, ...
        node_struct, ...
        node_name, ...
        new_node_name, ...
        model_checker)
    % create verification file
    [file_parent, mutant_lus_file_name, ~] = fileparts(mutant_lus_fpath);
    output_dir = fullfile(...
        file_parent, strcat(mutant_lus_file_name, '_build'));
    if ~exist(output_dir, 'dir'); mkdir(output_dir); end
    verif_lus_path = fullfile(...
        output_dir, strcat(mutant_lus_file_name, '_verif.lus'));

    if BUtils.isLastModified(mutant_lus_fpath, verif_lus_path)...
            && BUtils.isLastModified(lus_file_path, verif_lus_path)
        display_msg(...
            ['file ' verif_lus_path ' has been already generated'],...
            MsgType.DEBUG,...
            'Validation', '');
        return;
    end
    filetext1 = ...
        LustrecUtils.adapt_lustre_text(fileread(lus_file_path), model_checker, output_dir);
    sep_line =...
        '--******************** second file ********************';
    filetext2 = ...
        LustrecUtils.adapt_lustre_text(fileread(mutant_lus_fpath), model_checker, output_dir);
    filetext2 = regexprep(filetext2, '#open\s*<\w+>','');
    verif_line = ...
        '--******************** sVerification node *************';
    verif_node = LustrecUtils.construct_verif_node(...
        node_struct, node_name, new_node_name);

    verif_lus_text = sprintf('%s\n%s\n%s\n%s\n%s', ...
        filetext1, sep_line, filetext2, verif_line, verif_node);


    fid = fopen(verif_lus_path, 'w');
    fprintf(fid, verif_lus_text);
    fclose(fid);
end
