function code = print_lustrec(obj, backend) 

    if obj.withPar
        code = sprintf('(%s (%s))', ...
            obj.op, ...
            obj.expr.print(backend));
    else
        code = sprintf('%s (%s)', ...
            obj.op, ...
            obj.expr.print(backend));
    end
end
