classdef Kind2Utils2
    %KIND2UTILS Summary of this class goes here
    %   Detailed explanation goes here
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Copyright (c) 2019 United States Government as represented by the
    % Administrator of the National Aeronautics and Space Administration.
    % All Rights Reserved.
    % Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    properties
    end
    
    methods(Static = true)
        %% Check the lustre syntax
        [status, output] = checkSyntaxError(lus_file_path, KIND2, Z3)
        %% run kind2 with arguments
        [status, solver_output] = runKIND2(...
                verif_lus_path,...
                node, ...
                OPTS, KIND2, Z3, timeout, timeout_analysis)
        %% run compositional modular verification usin Kind2
        [valid, IN_struct] = extractKind2CEX(...
                verif_lus_path,...
                output_dir,...
                node, ...
                OPTS, KIND2, Z3)

        [valid, IN_struct] = extract_Kind2_Comp_Verif_answer(...
                lus_full_path, ...
                solver_output, ...
                file_name, ...
                output_dir)
        
        [IN_struct, time_max] = Kind2CEXTostruct(...
                node_struct, ...
                cex_xml, ...
                node_name)

    end
    
end

