function new_obj = changeArrowExp(obj, cond)

    new_obj = nasa_toLustre.lustreAst.IteExpr(obj.condition.changeArrowExp(cond),...
        obj.thenExpr.changeArrowExp(cond),...
        obj.ElseExpr.changeArrowExp(cond),...
        obj.OneLine);
end
