function new_obj = deepCopy(obj)

    new_obj = nasa_toLustre.lustreAst.IteExpr(...
        obj.condition.deepCopy(),...
        obj.thenExpr.deepCopy(),...
        obj.ElseExpr.deepCopy(),...
        obj.OneLine);
end
