function code = print_lustrec(obj, backend)

    if obj.OneLine
        code = sprintf('(if %s then %s else %s)', ...
            obj.condition.print(backend),...
            obj.thenExpr.print(backend), ...
            obj.ElseExpr.print(backend));
    else
        code = sprintf('(if %s then\n\t\t%s\n\t    else %s)', ...
            obj.condition.print(backend),...
            obj.thenExpr.print(backend), ...
            obj.ElseExpr.print(backend));
    end
    
end
