%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (c) 2019 United States Government as represented by the
% Administrator of the National Aeronautics and Space Administration.
% All Rights Reserved.
% Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [resetCode, status] = getTriggerCond(...
        triggerType, triggerDT, triggerInput, zero )
    %This function it differs from getResetCond as the rising/falling
    %conditions are not the same for resettableSubsystem Vs TriggeredSS
    %
    status = 0;
    if strcmp(triggerDT, 'bool')
        b_rising = triggerInput;
        b_falling = triggerInput;
    else
        %rising : Trigger execution of subsystem or model when the trigger signal 
        %rises from a negative or zero value to a positive value. 
        %If the initial value is negative, a rising signal to zero triggers execution.
        b_rising = nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.GT, triggerInput, zero);
        %falling : Trigger execution of subsystem or model when the trigger signal 
        %falls from a positive or a zero value to a negative value. 
        %If the initial value is positive, a falling signal to zero triggers execution.
        b_falling = nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.GTE, triggerInput, zero);
    end
    if strcmpi(triggerType, 'rising')
        resetCode = ...
            nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.ARROW, ...
                       nasa_toLustre.lustreAst.BoolExpr('false'),...
                       nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.AND,...
                                  b_rising, ...
                                  nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.NOT, ...
                                            nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.PRE, b_rising)...
                                            )...
                                 )...
                      );

    elseif strcmpi(triggerType, 'falling')
        resetCode = ...
            nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.ARROW, ...
                       nasa_toLustre.lustreAst.BoolExpr('false'),...
                       nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.AND,...
                                  nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.NOT, b_falling), ...
                                  nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.PRE, b_falling)...
                                 )...
                      );
    elseif strcmpi(triggerType, 'either')
        resetCode = ...
            nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.ARROW, ...
                       nasa_toLustre.lustreAst.BoolExpr('false'),...
                       nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.OR,...
                                  nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.AND,...
                                              b_rising, ...
                                              nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.NOT, ...
                                                        nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.PRE, b_rising)...
                                                        )...
                                             ),...
                                  nasa_toLustre.lustreAst.BinaryExpr(nasa_toLustre.lustreAst.BinaryExpr.AND,...
                                              nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.NOT, b_falling), ...
                                              nasa_toLustre.lustreAst.UnaryExpr(nasa_toLustre.lustreAst.UnaryExpr.PRE, b_falling)...
                                             )...
                                  )...
                      );
   
    elseif strcmpi(triggerType, 'function-call')
        resetCode = triggerInput;
    else
        resetCode = nasa_toLustre.lustreAst.VarIdExpr('');
        status = 1;
        return;
    end
end
