
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
function b = isIgnoredSampleTime(st_n, ph_n)
    b = st_n <= 0 || ph_n < 0 || ...
        (...
        (st_n == 1 ||  isinf(st_n) || isnan(st_n))...
        && (ph_n == 0 || isinf(ph_n) || isnan(ph_n))...
        );
end
