function code = print_kind2(obj, backend)

    args_str = nasa_toLustre.lustreAst.NodeCallExpr.getArgsStr(obj.nodeArgs, backend);
    code = sprintf('(restart %s every %s)(%s)', ...
        obj.nodeName, ...
        obj.cond.print(backend),...
        args_str);
end
