function [node, external_nodes, opens, abstractedNodes] = getORBitwiseUnsigned(n)
    import nasa_toLustre.lustreAst.*
    opens = {};
    abstractedNodes = {};
    external_nodes = {};
    
    %code = {};
    %code{1} = sprintf('( ((x mod 2) + (y mod 2) + (x mod 2)*(y mod 2))  mod 2)');
    args = cell(1, n);
    args{1} =   ...
        BinaryExpr(BinaryExpr.MOD,...
        BinaryExpr.BinaryMultiArgs(BinaryExpr.PLUS, ...
        {BinaryExpr(BinaryExpr.MOD, VarIdExpr('x'), IntExpr(2)), ...
        BinaryExpr(BinaryExpr.MOD, VarIdExpr('y'), IntExpr(2)), ...
        BinaryExpr(...
        BinaryExpr.MULTIPLY, ...
        BinaryExpr(BinaryExpr.MOD, VarIdExpr('x'), IntExpr(2)), ...
        BinaryExpr(BinaryExpr.MOD, VarIdExpr('y'), IntExpr(2)))...
        }),...
        IntExpr(2));
    for i=1:n-1
        v2_pown = 2^i;
        %code{end+1} = sprintf('%d*(((((x / %d) mod 2) + ((y / %d) mod 2) + ((x / %d) mod 2)*((y / %d) mod 2))) mod 2)',...
        %    v2_pown, v2_pown, v2_pown, v2_pown, v2_pown);
        x_term = BinaryExpr(...
            BinaryExpr.DIVIDE, VarIdExpr('x'), IntExpr(v2_pown));
        y_term = BinaryExpr(...
            BinaryExpr.DIVIDE, VarIdExpr('y'), IntExpr(v2_pown));
        args{i + 1} =   ...
            BinaryExpr(...
            BinaryExpr.MULTIPLY, ...
            IntExpr(v2_pown), ...
            BinaryExpr(BinaryExpr.MOD,...
            BinaryExpr.BinaryMultiArgs(BinaryExpr.PLUS, ...
            {BinaryExpr(BinaryExpr.MOD, x_term, IntExpr(2)), ...
            BinaryExpr(BinaryExpr.MOD, y_term, IntExpr(2)), ...
            BinaryExpr(...
            BinaryExpr.MULTIPLY, ...
            BinaryExpr(BinaryExpr.MOD, x_term, IntExpr(2)), ...
            BinaryExpr(BinaryExpr.MOD, y_term, IntExpr(2)))...
            }),...
            IntExpr(2))...
            );
    end
    %code = MatlabUtils.strjoin(code, ' \n\t+ ');
    rhs = BinaryExpr.BinaryMultiArgs(BinaryExpr.PLUS, args);
    node_name = strcat('_OR_Bitwise_Unsigned_', num2str(n));
    
    %             format = 'node %s (x, y: int)\nreturns(z:int);\nlet\n\t';
    %             format = [format, 'z = %s;\ntel\n\n'];
    %             node = sprintf(format, node_name, code);
    bodyElts{1} = LustreEq(VarIdExpr('z'), rhs);
    node = LustreNode();
    node.setName(node_name);
    node.setInputs({LustreVar('x', 'int'), LustreVar('y', 'int')});
    node.setOutputs(LustreVar('z', 'int'));
    node.setBodyEqs(bodyElts);
    node.setIsMain(false);
end