function [results, passed] = jc_0211(model)
    %4.3.4.1 jc_0211: Usable characters for Inport block and Outport block
    results = {};
    title = '4.3.4.1 jc_0211: Usable characters for Inport block and Outport block';
    passed = 0;
    results{end+1} = HtmlItem(title, ...
        {HtmlItem('Space in name', ...
                  HtmlItem('Passed', {}, 'green')), ...
         HtmlItem('Leading number in name', ...
                  HtmlItem('Passed', {}, 'green')), ...
         HtmlItem('Leading underscore in name', ...
                  HtmlItem('Passed', {}, 'green')), ...
         HtmlItem('Consecutive underscore in name', ...
                  HtmlItem('Passed', {}, 'green')), ...
         HtmlItem('Ends with underscore in name', ...
                  HtmlItem('Block X'))});
    
end