function newList = ppSignalNames(list)
    % get names from handles
    Names = arrayfun(@(x) get_param(x, 'Name'), list, 'UniformOutput',...
        false);
    %remove empty lines
    list = list(~strcmp(Names, ''));
    %add parent
    newList = arrayfun(@(x) ...
        sprintf('%s in %s', ...
        HtmlItem.removeHtmlKeywords(get_param(x, 'Name')), ...
        HtmlItem.addOpenCmd(get_param(x, 'Parent'))), ...
        list, 'UniformOutput', false);
end


