function r = isSimpleExpr(expr)

    r = isa(expr, 'nasa_toLustre.lustreAst.VarIdExpr')...
        || isa(expr, 'nasa_toLustre.lustreAst.IntExpr')...
        || isa(expr, 'nasa_toLustre.lustreAst.RealExpr')...
        || isa(expr, 'nasa_toLustre.lustreAst.BoolExpr')...
        || isa(expr, 'nasa_toLustre.lustreAst.EnumValueExpr');
end
