function TriggerinputExp = getTriggerValue(Cond, triggerInput, TriggerType, TriggerBlockDt, IncomingSignalDT)
    %% trigger value
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Copyright (c) 2017 United States Government as represented by the
    % Administrator of the National Aeronautics and Space Administration.
    % All Rights Reserved.
    % Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    L = nasa_toLustre.ToLustreImport.L;
    import(L{:})
    if strcmp(TriggerBlockDt, 'real')
        %suffix = '.0';
        zero = nasa_toLustre.lustreAst.RealExpr('0.0');
        one = nasa_toLustre.lustreAst.RealExpr('1.0');
        two = nasa_toLustre.lustreAst.RealExpr('2.0');
    else
        %suffix = '';
        zero = nasa_toLustre.lustreAst.IntExpr(0);
        one = nasa_toLustre.lustreAst.IntExpr(1);
        two = nasa_toLustre.lustreAst.IntExpr(2);
    end
    if strcmp(IncomingSignalDT, 'real')
        IncomingSignalzero = nasa_toLustre.lustreAst.RealExpr('0.0');
    else
        IncomingSignalzero = nasa_toLustre.lustreAst.IntExpr(0);
    end
    if strcmp(TriggerType, 'rising')
%                 sprintf(...
%                     '0%s -> if %s then 1%s else 0%s'...
%                     ,suffix, Cond, suffix, suffix );
        TriggerinputExp = ...
            nasa_toLustre.lustreAst.BinaryExpr(BinaryExpr.ARROW, ...
            zero, ...
            nasa_toLustre.lustreAst.IteExpr(Cond, one, zero)) ;
    elseif strcmp(TriggerType, 'falling')
%                 TriggerinputExp = sprintf(...
%                     '0%s -> if %s then -1%s else 0%s'...
%                     ,suffix, Cond, suffix, suffix );
        TriggerinputExp = ...
            nasa_toLustre.lustreAst.BinaryExpr(BinaryExpr.ARROW, ...
            zero, ...
            nasa_toLustre.lustreAst.IteExpr(Cond, ...
                    nasa_toLustre.lustreAst.UnaryExpr(UnaryExpr.NEG, one),...
                    zero)) ;
    elseif strcmp(TriggerType, 'function-call')
%                 TriggerinputExp = sprintf(...
%                     '0%s -> if %s then 2%s else 0%s'...
%                     ,suffix, Cond, suffix, suffix );
        TriggerinputExp = ...
            nasa_toLustre.lustreAst.BinaryExpr(BinaryExpr.ARROW, ...
            zero, ...
            nasa_toLustre.lustreAst.IteExpr(Cond, ...
                    two,...
                    zero)) ;
    else
        risingCond =nasa_toLustre.utils.SLX2LusUtils.getResetCode(...
            'rising', IncomingSignalDT, triggerInput, IncomingSignalzero );
%                 TriggerinputExp = sprintf(...
%                     '%s -> if %s then (if (%s) then 1%s else -1%s) else 0%s'...
%                     ,zero,  Cond, risingCond, suffix, suffix, suffix);
        TriggerinputExp = ...
            nasa_toLustre.lustreAst.BinaryExpr(BinaryExpr.ARROW, ...
            zero, ...
            nasa_toLustre.lustreAst.IteExpr(Cond, ...
                    nasa_toLustre.lustreAst.IteExpr(risingCond, one, nasa_toLustre.lustreAst.UnaryExpr(UnaryExpr.NEG, one)),...
                    zero)) ;
    end
end
