#!/bin/bash

################################################################################
#
# Installation script for cocoSim dependencies :
# - lustrec, zustre, kind2 in the default folder /tools/verifiers.
# - downloading standard libraries PP, IR and ME from github version of CoCoSim
#
# Author: Hamza BOURBOUH <hamza.bourbouh@nasa.gov>
#
# Copyright (c) 2017 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
################################################################################
####### Utils ###############
source bash_utils

####### Machine #############
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    machine="osx";;
    *)          machine="linux"
esac
####### Global Variables ####
install_dir="../tools/verifiers/$machine"
install_dir=$(abs_path "$install_dir")
build_dir="../tools/build"
build_dir=$(abs_path "$build_dir")

git_dir="$build_dir/github"

cocosim_url="https://github.com/coco-team/cocoSim2.git"
cocosim_branch="master"


cocoSim2_dir=$(abs_path "..")

####### Installing Zustre, Kind2 ########

if [[ -a "$install_dir/spacer/bin/z3" && -a "$install_dir/zustre/bin/zustre" && -a "$install_dir/kind2/bin/kind2" ]]; then
    success "z3, Zustre, Kind2 successfully installed in $install_dir"
else
    /bin/bash install_tools --prefix=$install_dir --builddir=$build_dir
fi

####### Download standard libraries PP and IR ########
if [ ! -d "$git_dir" ]; then
    if [ ! -d "$build_dir" ]; then
        mkdir "$build_dir"
    fi
    mkdir $git_dir
    cd $git_dir
    git init
    git remote add -f origin $cocosim_url
    #git config core.sparseCheckout true
    #echo "src/pp/" >> .git/info/sparse-checkout
    #echo "src/middleEnd/lustre_compiler/" >> .git/info/sparse-checkout
    git pull origin $cocosim_branch
else
    cd $git_dir
    git pull origin $cocosim_branch
fi

##STD_PP
if [ ! -d  "$cocoSim2_dir/src/frontEnd/pp/std_pp" ]; then
	mkdir  "$cocoSim2_dir/src/frontEnd/pp/std_pp"
fi
cp -r "$git_dir/src/frontEnd/pp/"* "$cocoSim2_dir/src/frontEnd/pp/std_pp/"
rm -f "$cocoSim2_dir/src/frontEnd/pp/std_pp/cocosim_pp.m"

##STD_IR
if [ ! -d  "$cocoSim2_dir/src/frontEnd/IR/std_IR" ]; then
	mkdir  "$cocoSim2_dir/src/frontEnd/IR/std_IR"
fi
cp -r "$git_dir/src/frontEnd/IR/"* "$cocoSim2_dir/src/frontEnd/IR/std_IR/"

##Lustre_compiler
if [ ! -d  "$cocoSim2_dir/src/middleEnd/lustre_compiler" ]; then
	mkdir  "$cocoSim2_dir/src/middleEnd/lustre_compiler"
fi
cp -r "$git_dir/src/middleEnd/lustre_compiler/"* "$cocoSim2_dir/src/middleEnd/lustre_compiler/"

##DOC
if [ ! -d  "$cocoSim2_dir/doc" ]; then
	mkdir  "$cocoSim2_dir/doc"
fi
cp -r "$git_dir/doc/"* "$cocoSim2_dir/doc/"

##libs
if [ ! -d  "$cocoSim2_dir/libs" ]; then
	mkdir  "$cocoSim2_dir/libs"
fi
cp -r "$git_dir/libs/"* "$cocoSim2_dir/libs/"

##Utils
cp -r "$git_dir/src/utils/"* "$cocoSim2_dir/src/Utils/"

##GUI
if [ ! -d  "$cocoSim2_dir/src/gui" ]; then
	mkdir  "$cocoSim2_dir/src/gui"
fi
cp -r "$git_dir/src/gui/"* "$cocoSim2_dir/src/gui/"

##Backends
cp -r "$git_dir/src/backEnd/verification/"* "$cocoSim2_dir/src/backEnd/verification/"