#!/bin/bash

################################################################################
#
# Installation script for cocoSim dependencies :
# - lustrec, zustre, kind2 in the default folder /tools/verifiers.
# - downloading standard libraries PP, IR and ME from github version of CoCoSim
#
# Author: Hamza BOURBOUH <hamza.bourbouh@nasa.gov>
#
# Copyright (c) 2017 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
################################################################################
####### Utils ###############
source bash_utils

####### Machine #############
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    machine="osx";;
    *)          machine="linux"
esac
####### Global Variables ####
install_dir="../tools/verifiers/$machine"
install_dir=$(abs_path "$install_dir")
build_dir="../tools/build"
build_dir=$(abs_path "$build_dir")
lustrec_url="https://cavale.enseeiht.fr/git/lustrec"
#lustrec_url="https://github.com/coco-team/lustrec.git"
lustrec_branch="master"
kind2_url="https://github.com/kind2-mc/kind2.git"
kind2_branch="develop"

git_dir="$build_dir/github"

cocosim_url="https://github.com/coco-team/cocoSim2.git"
cocosim_branch="cocosim_nasa"


cocoSim2_dir=$(abs_path "..")

####### Installing Zustre, Kind2 ########

#if [[ -a "$install_dir/spacer/bin/z3" && -a "$install_dir/zustre/bin/zustre" && -a "$install_dir/kind2/bin/kind2" ]]; then
#    success "z3, Zustre, Kind2 successfully installed in $install_dir"
#else
    /bin/bash install_tools --prefix=$install_dir --builddir=$build_dir  --lustrec-url=$lustrec_url --lustrec-branch=$lustrec_branch
#fi


