################################################################################
#
# Installation Makefile for cocoSim dependencies :
# Author: Hamza BOURBOUH <hamza.bourbouh@nasa.gov>
#
# Copyright (c) 2017 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
################################################################################
####### Utils ###############
IR_path = "../src/frontend/IR/std_IR"
std_pp_path = "../src/frontEnd/pp/std_pp"
build_dir = "../tools/build"

install: 
	./install_cocosim

clean:
	rm -rf $(IR_path)/* $(std_pp_path)/* $(build_dir)