function code = print_kind2(obj, backend)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%    % Copyright (c) 2019 United States Government as represented by the
    % Administrator of the National Aeronautics and Space Administration.
    % All Rights Reserved.
    % Author: Hamza Bourbouh <hamza.bourbouh@nasa.gov>
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    args_str = nasa_toLustre.lustreAst.NodeCallExpr.getArgsStr(obj.nodeArgs, backend);
    if obj.has_restart
        code = sprintf('(activate %s every %s restart every %s)(%s)', ...
            obj.nodeName, ...
            obj.activate_cond.print(backend),...
            obj.restart_cond.print(backend), ...
            args_str);
    else
        code = sprintf('(activate %s every %s)(%s)', ...
            obj.nodeName, ...
            obj.activate_cond.print(backend),...
            args_str);
    end
end
