
function Values = get_random_values(time, nb_steps, min, max, dim, dt)
    [isBus, bus] = SLXUtils.isSimulinkBus(dt);
    lus_dt =nasa_toLustre.utils.SLX2LusUtils.get_lustre_dt(dt);
    if isBus
        Values = SLXUtils.construct_random_bus_values(bus, time, nb_steps, min, max, dim);
    elseif strcmp(lus_dt,'bool')
        Values = timeseries(...
            LusValidateUtils.construct_random_booleans(nb_steps, min, max, dim), ...
            time);
    elseif strcmp(dt,'int')
        Values = timeseries(...
            LusValidateUtils.construct_random_integers(nb_steps, min, max, 'int32', dim), ...
            time);

    elseif MatlabUtils.contains(dt,'int')
        Values = timeseries(...
            LusValidateUtils.construct_random_integers(nb_steps, min, max, dt, dim), ...
            time);
    elseif strcmp(dt,'single')
        Values = timeseries(...
            single(LusValidateUtils.construct_random_doubles(nb_steps, min, max, dim)), ...
            time);
    else
        Values = timeseries(...
            LusValidateUtils.construct_random_doubles(nb_steps, min, max, dim), ...
            time);
    end
end
